spring:
  main:
    web-application-type: none
  datasource:
    url: jdbc:mysql://localhost:3306/groove-db
    username: bambi
    password: Gr00v3
  jpa:
    hibernate:
      ddl-auto: update
    properties:
        dialect: org.hibernate.dialect.MySQLDialect